
namespace Cmune.Realtime.Photon.Client
{
  public enum NetworkState
  {
    STATE_NPEER_CREATED = 0,
    STATE_CONNECT = 1,
    STATE_CONNECTING = 2,
    STATE_CONNECTED = 3,
    STATE_JOINING = 4,
    STATE_ERROR_JOINING = 5,
    STATE_JOINED = 6,
    STATE_LEAVE = 7,
    STATE_LEAVING = 8,
    STATE_ERROR_LEAVING = 9,
    STATE_LEFT = 10,     STATE_ERROR_CONNECTING = 11,     STATE_RECEIVING = 12,     STATE_DISCONNECTING = 13,     STATE_DISCONNECTED = 14,     STATE_JOIN = 15,     STATE_DISCONNECT = 16,     STATE_UNDEFINED = 100,   }
}
