// Decompiled with JetBrains decompiler
// Type: System.Xml.Schema.XmlTypeCode
// Assembly: System.Xml, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
// MVID: A6093E4D-5C47-4D02-9BF3-E0EBDD0B6ACE
// Assembly location: C:\Program Files (x86)\Steam\steamapps\common\UberStrike_v4-3-10\UberStrike_Data\Managed\System.Xml.dll

namespace System.Xml.Schema
{
  public enum XmlTypeCode
  {
    None,
    Item,
    Node,
    Document,
    Element,
    Attribute,
    Namespace,
    ProcessingInstruction,
    Comment,
    Text,
    AnyAtomicType,
    UntypedAtomic,
    String,
    Boolean,
    Decimal,
    Float,
    Double,
    Duration,
    DateTime,
    Time,
    Date,
    GYearMonth,
    GYear,
    GMonthDay,
    GDay,
    GMonth,
    HexBinary,
    Base64Binary,
    AnyUri,
    QName,
    Notation,
    NormalizedString,
    Token,
    Language,
    NmToken,
    Name,
    NCName,
    Id,
    Idref,
    Entity,
    Integer,
    NonPositiveInteger,
    NegativeInteger,
    Long,
    Int,
    Short,
    Byte,
    NonNegativeInteger,
    UnsignedLong,
    UnsignedInt,
    UnsignedShort,
    UnsignedByte,
    PositiveInteger,
    YearMonthDuration,
    DayTimeDuration,
  }
}
